---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k1s
  labels:
    app: k1s
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k1s
  template:
    metadata:
      labels:
        app: k1s
    spec:
      containers:
        - name: hello-server
          image: ghcr.io/mohammadne/middleman/servers:develop
          imagePullPolicy: Always
          ports:
            - containerPort: 1378
          volumeMounts:
            - name: k1s-config
              mountPath: /bin/config.yaml
              subPath: config.yaml
      volumes:
        - name: k1s-config
          configMap:
            name: k1s-config
