name: build

on: [push]

env:
  registry: ghcr.io

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command: [servers, proxy]
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: ${{ env.registry }}/${{ github.actor }}/middleman/${{ matrix.command }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: "Build and push Docker image"
        uses: docker/build-push-action@v2
        with:
          file: "Dockerfile"
          context: .
          platforms: linux/amd64
          push: true
          build-args: ${{ matrix.command }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
